const express = require('express');
const router = express.Router();

router.get('/', (req, res) => { res.send('Connected to the API successfully!'); });

router.use('/contacts', require('./contacts'));

module.exports = router;